DROP TABLE MYBATISPLUS_USER PURGE;
CREATE TABLE MYBATISPLUS_USER
  (
    ID    NUMBER NOT NULL ,
    NAME  VARCHAR(30) NULL ,
    AGE   NUMBER NULL ,
    EMAIL VARCHAR(50) NULL,
    CONSTRAINT "mybatisplus_user_PK" PRIMARY KEY ("ID")
  );

DELETE FROM MYBATISPLUS_USER;
INSERT INTO MYBATISPLUS_USER (ID, NAME, AGE, EMAIL) VALUES (1, 'Jone', 18, 'test1@baomidou.com');
INSERT INTO MYBATISPLUS_USER (ID, NAME, AGE, EMAIL) VALUES (2, 'Jack', 20, 'test2@baomidou.com');
INSERT INTO MYBATISPLUS_USER (ID, NAME, AGE, EMAIL) VALUES (3, 'Tom', 28, 'test3@baomidou.com');
INSERT INTO MYBATISPLUS_USER (ID, NAME, AGE, EMAIL) VALUES (4, 'Sandy', 21, 'test4@baomidou.com');
INSERT INTO MYBATISPLUS_USER (ID, NAME, AGE, EMAIL) VALUES (5, 'Billie', 24, 'test5@baomidou.com');
COMMIT;